apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: wordpress
  labels:
    app: wp-mysql
    tier: db
spec:
  ports:
  - port: 3306
  selector:
    app: wp-mysql
    tier: db
  clusterIP: None
